# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RIBs-Tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RIBs-Tutorial
  pod 'RIBs', '~> 0.9'
  pod "SnapKit"

  target 'RIBs-TutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RIBs-TutorialUITests' do
    # Pods for testing
  end

end
